# Actividad Práctica

## Objetivo

El objetivo de esta actividad es familiarizarse con los comandos básicos de Docker y aprender a gestionar contenedores de manera eficiente.

## Instrucciones

1. Inicia un contenedor de la imagen "nginx" en segundo plano utilizando el comando **docker run**. Asegúrate de mapear el puerto 8080 del host al puerto 80 del contenedor.
2. Detén y elimina el contenedor que acabas de crear utilizando los comandos Docker apropiados.
3. Crea un nuevo contenedor con la imagen "alpine" y ejecuta un terminal interactivo dentro de él.
4. Desde el contenedor alpine, instala el paquete curl utilizando el gestor de paquetes apk.
5. Crea una imagen llamada "alpine-curl" a partir de este contenedor modificado.

Recuerda que puedes consultar la documentación de Docker si necesitas ayuda con los comandos.

## Entregables:

- Imagen Docker "alpine-curl" disponible localmente.

<details>
  <summary>Resolución de la Actividad Práctica</summary>

- Iniciar un contenedor Nginx:

``` bash
docker run -d -p 8080:80 --name my-nginx nginx
```
Detener y eliminar el contenedor Nginx:

``` bash
docker stop my-nginx
docker rm my-nginx
```
Crear un contenedor Alpine interactivo:

``` bash
docker run -it --name my-alpine alpine /bin/sh
```
Instalar el paquete curl desde el contenedor Alpine:

``` bash
apk add --no-cache curl
```
Crear una nueva imagen "alpine-curl":

``` bash
docker commit my-alpine alpine-curl
```
</details>
