# Actividad Práctica

## Objetivo

El objetivo de esta actividad es aplicar buenas prácticas y medidas de seguridad al trabajar con Docker.

## Instrucciones

1. Utiliza la herramienta Snyk para escanear la imagen "alpine:latest" en busca de vulnerabilidades.
2. Implementa una política de etiquetado para las imágenes Docker que siga las mejores prácticas. Por ejemplo, podrías incluir información sobre la versión del software y la fecha de creación en las etiquetas.
3. Utiliza la herramienta "docker-compose lint" para verificar la validez de tu archivo Docker Compose. Asegúrate de corregir cualquier advertencia o error que encuentres.
4. Implementa una red de contenedores utilizando el comando `docker network create`. Asegúrate de que solo los contenedores que necesitan comunicarse entre sí tengan acceso a esta red.
5. Crea un archivo ".dockerignore" para excluir archivos y directorios innecesarios en la construcción de imágenes Docker. Esto puede ayudar a reducir el tamaño de tus imágenes y a evitar la inclusión accidental de información sensible.

Recuerda que puedes consultar la documentación de Docker y Snyk si necesitas ayuda con los comandos.

## Entregables:

- Capturas de pantalla del escaneo de vulnerabilidades.
- Política de etiquetado para imágenes Docker.
- Resultado de la verificación del archivo Docker Compose.
- Documento explicando la implementación de la red de contenedores.
- Archivo ".dockerignore".


<details>
  <summary>Resolución de la Actividad Práctica</summary>

Escaneo de vulnerabilidades:

``` bash
snyk container test alpine:latest
```
Política de etiquetado (ejemplo):

Se etiquetarán las imágenes con el formato "versión-año-mes-día" (ejemplo: 1.0-20230115).

Verificación del archivo Docker Compose:

``` bash
docker-compose config
```
Implementación de una red de contenedores:

``` bash
docker network create my-network
```
Archivo ".dockerignore" (ejemplo):

``` bash
node_modules
.git
.env
```
</details>

## Rubrica de Evaluación:

- Escaneo de vulnerabilidades realizado con éxito: 4 puntos
- Correcta implementación de la política de etiquetado: 4 puntos
- Validación exitosa del archivo Docker Compose: 4 puntos
- Implementación adecuada de la red de contenedores: 4 puntos
- Correcta configuración del archivo ".dockerignore": 4 puntos