project:
  type: book
  output-dir: docs

book:
  title: "Docker 2023"
  author: "Diego Saavedra"
  output-file: "curso_docker_2023"  
  date: today
  date-format: medium
  favicon: /images/docker.png
  description: ¡Bienvenidos al Curso Completo de Docker! Este curso te llevará desde los conceptos fundamentales de Docker hasta el dominio de la plataforma líder en contenedores. Aprenderás a utilizar Docker para desarrollar, desplegar y escalar aplicaciones eficientemente. Este curso está diseñado para principiantes y aquellos que desean profundizar en Docker, ofreciendo una combinación de teoría y ejercicios prácticos. Contribuye, aprende y disfruta de este emocionante viaje en el mundo de Docker y los contenedores. ¡Esperamos que aproveches al máximo este curso!
  keyword: Docker, Contenedores, Imágenes, Dockerfile, Docker Compose, Orquestación, Multi-Stage Builds, Volúmenes, Redes de Contenedores, Escaneo de Imágenes, Buenas Prácticas, Seguridad, Despliegue, Desarrollo Web, Virtualización, Desarrollo Ágil, Eficiencia, Docker Hub, DevOps, Escalabilidad, Kubernetes, Administración de Contenedores.
  url: https://github.com/statick88/course_docker
  page-navigation: true
  sidebar: 
    logo: /images/docker.png
    collapse-level: 1

  repo-url: https://github.com/statick88/course_docker
  repo-subdir: book
  repo-branch: main
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: /images/docker.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Curso Docker"
      chapters: 
        - unidades/unidad0.qmd
        - unidades/ejercicios0.qmd
        - unidades/unidad1.qmd
        - unidades/ejercicios1.qmd
        - unidades/unidad2.qmd
        - unidades/ejercicios2.qmd
        - unidades/unidad3.qmd
        - unidades/ejercicios3.qmd
        - unidades/unidad4.qmd
        - unidades/ejercicios4.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Curso de Docker 2023"
    group-position: 0
    creator: "Lcdo. Diego Saavedra Mgtr."
    rights: "© Statick | 2023"